/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "about": { "text": "NATO Phonetic Widget", "view": "DC.Text" },
    "copyright": { "text": "Copyright 2011  Gopal Venkatesan", "view": "DC.Text" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "fullNameBtn": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "fullNameBtnClick", "rightImageWidth": 5, "text": "Choose my full name" },
    "infobutton": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "orText": { "text": "OR", "view": "DC.Text" },
    "phoneticList": { "autoHideScrollbars": true, "creationFunction": "CreateScrollArea", "hasVerticalScrollbar": true, "scrollbarDivSize": 18, "scrollbarMargin": 6, "spacing": 4 },
    "rights": { "text": "All rights reserved.", "view": "DC.Text" },
    "whatsthis": { "text": "What's this?", "view": "DC.Text" }
};



